<?php
define('DB_NAME','dbuser');
define('DB_USER','admin_db');
define('DB_PASSWORD','123456');
define('DB_HOST','localhost');
//define('DB_NAME','shop');
//define('DB_USER','plomba');
//define('DB_PASSWORD','Olke632id&dje*7dje6hdne7&&dGGtde');
//define('DB_HOST','mysql');
//define('DB_HOST','192.168.0.113');
define('DB_CHARSET','utf8');